title: Backend Engineering Bootcamp Handbook
description: A practical backend-focused engineering onboarding handbook for interns.

baseurl: "/engineering-bootcamp-handbook"
url: "https://indapmgr.github.io"

markdown: kramdown

plugins:
  - jekyll-seo-tag
