title: Intern Engineering Handbook
description: A practical full-stack engineering onboarding handbook for interns.
theme: minima

baseurl: ""
url: "https://indapmgr.github.io"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - docs/index.md
